[project]
name = ""
version = ""
description = ""
authors = [
    {name = "pynchia", email = "pynchia@gmail.com"},
]
license = {text = "MIT"}
dependencies = [
    "fastapi[all]>=0.104.1",
]
requires-python = ">=3.11"
